name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: ⚡ Cache rust
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: ⚡ Cache nodejs
      uses: actions/cache@v2
      with:
        path: |
          ~/pilcom/node_modules
        key: ${{ runner.os }}-pilcom-node-modules
    - name: Install pilcom
      run: cd pilcom && npm install
    - name: Install z3
      run: sudo apt-get install -y z3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: cargo clippy --all --all-features -- -D warnings
    - name: Format
      run: cargo fmt --check --verbose
